name: C/C++ CI

on:
  push:
    branches: [ master, auto_testing]
  pull_request:
    branches: [ master, auto_testing]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - run: sudo apt-get update -qq
    - run: sudo apt-get install -qq g++-8 cmake build-essential python3-pip python3-virtualenv nodejs tar gzip libpthread-stubs0-dev libc6-dbg gdb
    - run: sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
    - name: run-tests
      run: make 
      working-directory: tests
